FROM ghcr.io/kengo-k/dev-base-ubuntu:202305222318-61621c2

LABEL org.opencontainers.image.description="NodeJsによる開発用イメージ(v19.8.1)"

SHELL ["/bin/bash", "-c"]
RUN source ~/.bashrc && \
  asdf plugin add nodejs