name: build docker image and push image to GHCR

on:
  push:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      changed_dockerfiles: ${{ steps.set_output.outputs.changed_dockerfiles }}
    
    steps:

    # イメージのタグに付与する日付文字列を変数にセットしておく
    - name: set up environment variables
      run: |
        echo "DATE_TAG=$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    # 前回PUSHされた際のコミットを取得する
    - name: checkout before commit
      uses: actions/checkout@v2
      with:
        ref: ${{ github.event.before }}

    # 前回PUSHされたコミットから最新のコミットまでを取得する
    - name: fetch changed between before and latest
      run: |
        git fetch origin $GITHUB_SHA:refs/remotes/origin/main
        git checkout $GITHUB_SHA

    # 変更のあったすべてのDockerfileの一覧を取得する
    - name: find changed Dockerfiles
      id: find_changed_dockerfiles
      run: |
        echo "previous commit: ${{ github.event.before }}"
        echo "latest commit: ${{ github.sha }}"
        changed_dockerfiles=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep yaml || true)
        echo $changed_dockerfiles
        echo "::set-output name=changed_dockerfiles::$changed_dockerfiles"

  build:
    needs: prepare
    # if: needs.prepare.outputs.changed_dockerfiles != ''
    runs-on: ubuntu-latest
    
    steps:
    - name: aaa
      run: |
        echo "prev output: ${{ prepare.outputs.changed_dockerfiles }}"
    # - name: Build and push Docker images
    #   if: ${{ steps.find_changed_dockerfiles.outputs.changed_dockerfiles }}
    #   run: |
    #     changed_dockerfiles="${{ steps.find_changed_dockerfiles.outputs.changed_dockerfiles }}"
    #     for dockerfile in $changed_dockerfiles; do
    #       tags="ghcr.io/${{ github.actor }}/dev-base:${{ env.DATE_TAG }}-$GITHUB_SHA,ghcr.io/${{ github.actor }}dev-base:latest"
    #       echo "Building and pushing $image_name with context $context and tags $tags"
    #       docker build -t $tags -f $dockerfile
    #       for tag in $(echo $tags | tr "," "\n"); do
    #         docker push $tag
    #       done
    #     done

    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v1

    # - name: Login to GitHub Container Registry
    #  uses: docker/login-action@v1
      # with:
      #   registry: ghcr.io
      #   username: ${{ github.actor }}
      #   password: ${{ secrets.GITHUB_TOKEN }}
